(()=>{'use strict';
const API='https://wowmycxjbwillqduhyjb.supabase.co/functions/v1/survey-api';const $=id=>document.getElementById(id);const LS='plant_recorder_v5_session';const scoreNames=['感知绿化程度','感知植物多样性','植物色彩丰富度','景观自然感','景观设计层次感','软硬景观协调性','街道尺度宜人度','感知视线通透性','整洁感','基础设施丰富度','铺装质量感知','安全感'];const species=['狗牙根','马唐','莲子草','香附子','黄独','牛筋草','打碗花','艾草','白三叶','酢浆草','葛','鬼针草','大车前草','黄鹌菜','楝','桑','水杉','紫薇','红叶石楠'];const aliases={'狗芽根':'狗牙根','狗牙跟':'狗牙根','马糖':'马唐','马塘':'马唐','莲籽草':'莲子草','连子草':'莲子草','香夫子':'香附子','香父子':'香附子','黄毒':'黄独','黄度':'黄独','牛津草':'牛筋草','牛精草':'牛筋草','大碗花':'打碗花','打完花':'打碗花','爱草':'艾草','白车轴草':'白三叶','白三叶草':'白三叶','醋浆草':'酢浆草','红叶石南':'红叶石楠','红叶石兰':'红叶石楠'};const cn={'零':0,'〇':0,'一':1,'二':2,'两':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9};let sess=null,state=null,siteId='',sampleId='',rec=null,active=false,keep=false,timer=null,last='';window.recorderState=()=>toExportState();window.recorderPersist=()=>{};
async function api(action,p={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token:sess?.token,...p})});const j=await r.json();if(!r.ok)throw new Error(j.error||'操作失败');return j}
function store(){localStorage.setItem(LS,JSON.stringify(sess))}function restore(){try{sess=JSON.parse(localStorage.getItem(LS)||'null')}catch(e){sess=null}}
function today(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function showLogin(){document.getElementById('loginCard').style.display='block';document.getElementById('mainApp').style.display='none'}function showApp(){document.getElementById('loginCard').style.display='none';document.getElementById('mainApp').style.display='block';$('who').textContent=`${sess.group.group_code}组 · ${sess.member_name}`}
function mapState(raw){const survey=raw.survey,sites=(raw.sites||[]).map(s=>({...s,samples:(raw.samples||[]).filter(q=>q.site_id===s.id).map(q=>({...q,records:(raw.records||[]).filter(r=>r.sample_id===q.id)}))}));return{survey,sites}}
function toExportState(){if(!state)return{date:$('date').value,grid:$('grid').value,district:$('district').value,sites:[]};return{date:state.survey.survey_date,grid:state.survey.grid_no,district:state.survey.district,sites:state.sites.map(s=>({code:s.code,loc:s.loc,road:s.road,motor:s.motor,slow:s.slow,canopy:s.canopy,dominant:s.dominant,community:s.community,material:s.material,water:s.water,bio:s.bio,maint:s.maint,scores:s.scores||{},samples:s.samples.map(q=>({code:q.code,records:q.records.map(r=>({plant:r.plant,height:r.height,length:r.length,width:r.width,cover:r.cover,type:r.type,growth:r.growth,note:r.note}))}))}))}}
function curSite(){return state?.sites.find(s=>s.id===siteId)}function curSample(){return curSite()?.samples.find(q=>q.id===sampleId)}function status(msg){$('sync').textContent=msg}
function render(){if(!state)return;$('date').value=state.survey.survey_date;$('grid').value=state.survey.grid_no;$('district').value=state.survey.district;let st=curSite();if(!st&&state.sites.length){siteId=state.sites[0].id;st=state.sites[0]}if(st&&!sampleId&&st.samples.length)sampleId=st.samples[0].id;renderSites();renderSiteForm();renderSamples();renderRows();kpis()}
function renderSites(){let b=$('siteTabs');b.innerHTML='';state.sites.forEach(s=>{let x=document.createElement('button');x.className=s.id===siteId?'active':'soft';x.textContent=s.code+'样地';x.onclick=()=>{siteId=s.id;sampleId=s.samples[0]?.id||'';render()};b.appendChild(x)})}
function renderSiteForm(){let s=curSite();if(!s){['siteCode','siteLoc','road','motor','slow','canopy','dominant','material','water','bio','maint'].forEach(i=>$(i).value='');return}const map={siteCode:'code',siteLoc:'loc',road:'road',motor:'motor',slow:'slow',canopy:'canopy',dominant:'dominant',community:'community',material:'material',water:'water',bio:'bio',maint:'maint'};Object.entries(map).forEach(([i,k])=>$(i).value=s[k]||'');let box=$('scores');box.innerHTML='';scoreNames.forEach((n,i)=>{let d=document.createElement('div');d.innerHTML=`<label>${n}</label><input id="sc${i}" inputmode="numeric" value="${String(s.scores?.[n]||'').replace(/"/g,'&quot;')}">`;box.appendChild(d);d.querySelector('input').onchange=saveSite})}
function renderSamples(){let s=curSite(),b=$('sampleTabs');b.innerHTML='';(s?.samples||[]).forEach(q=>{let x=document.createElement('button');x.className='sample '+(q.id===sampleId?'active':'');x.textContent=q.code;x.onclick=()=>{sampleId=q.id;renderSamples();renderRows();$('sampleCode').value=q.code;$('ps').value=q.code};b.appendChild(x)});let q=curSample();$('sampleCode').value=q?.code||'';$('ps').value=q?.code||''}
function renderRows(){let q=curSample(),b=$('rows');b.innerHTML='';(q?.records||[]).forEach((r,i)=>{let tr=document.createElement('tr');[i+1,r.plant,r.height,[r.length,r.width].filter(Boolean).join('×'),r.cover,r.type,r.growth,r.created_by||'',r.note].forEach(v=>{let td=document.createElement('td');td.textContent=v||'';tr.appendChild(td)});let td=document.createElement('td'),bt=document.createElement('button');bt.textContent='删';bt.className='danger';bt.onclick=async()=>{if(!confirm('删除这条记录？'))return;await api('delete_record',{record_id:r.id});await refresh()};td.appendChild(bt);tr.appendChild(td);b.appendChild(tr)})}
function kpis(){let q=0,r=0;state.sites.forEach(s=>{q+=s.samples.length;s.samples.forEach(x=>r+=x.records.length)});$('kc1').textContent=state.sites.length+'个样地';$('kc2').textContent=q+'个样方';$('kc3').textContent=r+'条记录'}
async function refresh(silent=false){if(!state?.survey?.id)return;try{let j=await api('get_state',{survey_id:state.survey.id});let oldSite=siteId,oldSample=sampleId;state=mapState(j.state);siteId=state.sites.some(s=>s.id===oldSite)?oldSite:state.sites[0]?.id||'';let s=curSite();sampleId=s?.samples.some(q=>q.id===oldSample)?oldSample:s?.samples[0]?.id||'';render();if(!silent)status('已同步 '+new Date().toLocaleTimeString())}catch(e){status('同步失败：'+e.message)}}
async function openSurvey(){try{status('正在进入网格…');let j=await api('open_survey',{survey_date:$('date').value,grid_no:$('grid').value,district:$('district').value});state=mapState(j.state);siteId=state.sites[0]?.id||'';sampleId=state.sites[0]?.samples[0]?.id||'';if(!state.sites.length){await addSite()}else render();status('共享数据已连接')}catch(e){alert(e.message);status('未连接')}}
async function addSite(){let used=new Set(state?.sites.map(s=>s.code)||[]),code='A';for(let i=0;i<26;i++){let c=String.fromCharCode(65+i);if(!used.has(c)){code=c;break}}let j=await api('save_site',{survey_id:state.survey.id,site:{code,loc:`${state.survey.grid_no}号网格${code}样地`,scores:{}}});await refresh(true);siteId=j.site.id;render();await addSample()}
async function saveSite(){let s=curSite();if(!s)return;let scores={};scoreNames.forEach((n,i)=>scores[n]=$('sc'+i)?.value||'');let payload={id:s.id,code:$('siteCode').value,loc:$('siteLoc').value,road:$('road').value,motor:$('motor').value,slow:$('slow').value,canopy:$('canopy').value,dominant:$('dominant').value,community:$('community').value,material:$('material').value,water:$('water').value,bio:$('bio').value,maint:$('maint').value,scores};try{await api('save_site',{survey_id:state.survey.id,site:payload});status('样地信息已保存');await refresh(true)}catch(e){alert(e.message)}}
async function addSample(){let s=curSite();if(!s)return;let n=1,used=new Set(s.samples.map(q=>q.code));while(used.has(s.code+n))n++;let j=await api('save_sample',{site_id:s.id,sample:{code:s.code+n}});await refresh(true);sampleId=j.sample.id;render()}
async function saveSample(){let q=curSample(),s=curSite();if(!q||!s)return;let j=await api('save_sample',{site_id:s.id,sample:{id:q.id,code:$('sampleCode').value}});sampleId=j.sample.id;await refresh(true)}
async function addRecord(){let q=curSample();if(!q)return alert('请先新建样方');let r={plant:$('pp').value.trim(),height:$('ph').value.trim(),length:$('pl').value.trim(),width:$('pw').value.trim(),cover:$('pc').value.trim(),type:$('pt').value,growth:$('pg').value.trim(),note:$('pn').value.trim()};if(!r.plant)return alert('请先确认植物种名');try{status('正在共享保存…');await api('add_record',{sample_id:q.id,record:r});['pp','ph','pl','pw','pc','pg','pn'].forEach(i=>$(i).value='');$('pt').value='';$('speech').value='';last='';await refresh();}catch(e){alert(e.message)}}
function cInt(s){if(/^\d+$/.test(s))return+s;let t=0,n=0;for(let ch of s){if(ch in cn)n=cn[ch];else if(ch==='十'){t+=(n||1)*10;n=0}else if(ch==='百'){t+=(n||1)*100;n=0}}return t+n}function cNum(s){s=String(s||'').replace(/厘米|公分|cm|CM|％|%/g,'').replace(/^百分之/,'');if(/^\d+(\.\d+)?$/.test(s))return+s;let p=s.split(/[点\.]/),n=cInt(p[0]);if(p[1]){let f='';for(let ch of p[1])f+=ch in cn?cn[ch]:ch;return+(n+'.'+f)}return n}const NP='[零〇一二两三四五六七八九十百点\\.\\d]+';function norm(t){t=(t||'').replace(/[，、；;]/g,',').replace(/\s+/g,' ').trim();Object.entries(aliases).forEach(([a,b])=>t=t.split(a).join(b));return t}function numAfter(t,a){for(let x of a){let m=t.match(new RegExp(x+'[：: ]*(?:约|大概)?(?:百分之)?('+NP+')'));if(m)return cNum(m[1])}return null}function dims(t){let m=t.match(new RegExp('(?:长宽|尺寸)?[：: ]*(?:约)?('+NP+')\\s*(?:乘|×|x|X|\\*|比)\\s*('+NP+')'));return m?[cNum(m[1]),cNum(m[2])]:[null,null]}function plant(t){return species.find(x=>t.includes(x))||''}function type(t){return/人工|栽培/.test(t)?'人工栽培':/野生|自生/.test(t)?'野生自生':''}function parse(raw){let t=norm(raw),p=plant(t),h=numAfter(t,['平均高度','高度','高']),[l,w]=dims(t),c=numAfter(t,['盖度','覆盖度','覆盖']),g=numAfter(t,['生长状况','长势','生长']),ty=type(t);let miss=[];if(!p)miss.push('种名');if(h==null)miss.push('高度');if(l==null)miss.push('长×宽');if(c==null)miss.push('盖度');if(!ty)miss.push('类型');if(!(g>=1&&g<=5))miss.push('长势');return{raw,p,h,l,w,c,g:g>=1&&g<=5?g:'',ty,sm:curSample()?.code||'',miss}}function fill(x){$('speech').value=x.raw;$('pp').value=x.p;$('ph').value=x.h??'';$('pl').value=x.l??'';$('pw').value=x.w??'';$('pc').value=x.c??'';$('pg').value=x.g;$('pt').value=x.ty;$('ps').value=x.sm;$('pn').value=x.miss.length?'待确认：'+x.miss.join('、'):'';$('hint').innerHTML=x.miss.length?'<span class="bad">⚠️ '+x.miss.join('、')+'</span>':'<span class="good">✅ 可直接加入</span>'}function score(t){let x=parse(t),s=0;if(x.p)s+=6;if(x.l!=null)s+=3;if(x.h!=null)s++;if(x.c!=null)s++;if(x.ty)s++;if(x.g)s++;return s}
function micUI(on,msg){$('mic').classList.toggle('on',on);$('mic').textContent=on?'🛑持续监听中，点此停止':'🎙️开始持续监听';if(msg)$('speechStatus').textContent=msg}function start(){if(!keep||active)return;try{rec.start()}catch(e){timer=setTimeout(start,500)}}function speechSetup(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){$('mic').disabled=true;$('speechStatus').textContent='当前浏览器不支持网页语音，请用手机键盘语音输入';return}rec=new R;rec.lang='zh-CN';rec.continuous=true;rec.interimResults=true;rec.maxAlternatives=5;rec.onstart=()=>{active=true;micUI(true,'持续监听中；自动断开会自动重连。')};rec.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){let a=e.results[i];if(!a.isFinal){$('speech').value=a[0].transcript;continue}let best=a[0].transcript,bs=-1;for(let j=0;j<a.length;j++){let s=score(a[j].transcript);if(s>bs){bs=s;best=a[j].transcript}}if(best!==last){last=best;fill(parse(best))}}};rec.onerror=e=>{active=false;if(['not-allowed','audio-capture'].includes(e.error)){keep=false;micUI(false,'麦克风权限或占用异常')}else if(keep)$('speechStatus').textContent='短暂中断，正在重连…'};rec.onend=()=>{active=false;if(keep){timer=setTimeout(start,350)}else micUI(false)};$('mic').onclick=()=>{if(keep){keep=false;clearTimeout(timer);try{rec.stop()}catch(e){};micUI(false,'已停止')}else{keep=true;last='';start()}}}
async function login(create){try{let group_code=$('groupCode').value.trim(),password=$('groupPwd').value,member_name=$('memberName').value.trim();let j=await api(create?'create_group':'join_group',{group_code,password,member_name});sess={token:j.token,group:j.group,member_name:j.member_name};store();showApp();$('date').value=today();status('已进入共享小组');}catch(e){alert(e.message)}}
$('createGroup').onclick=()=>login(true);$('joinGroup').onclick=()=>login(false);$('logout').onclick=()=>{localStorage.removeItem(LS);sess=null;state=null;showLogin()};$('openSurvey').onclick=openSurvey;$('addSite').onclick=addSite;$('delSite').onclick=async()=>{let s=curSite();if(s&&confirm('删除当前样地及全部样方？')){await api('delete_site',{site_id:s.id});siteId='';sampleId='';await refresh()}};$('saveSite').onclick=saveSite;$('addSample').onclick=addSample;$('delSample').onclick=async()=>{let q=curSample();if(q&&confirm('删除当前样方？')){await api('delete_sample',{sample_id:q.id});sampleId='';await refresh()}};$('sampleCode').onchange=saveSample;$('parse').onclick=()=>fill(parse($('speech').value));$('clearSpeech').onclick=()=>{$('speech').value=''};$('addRecord').onclick=addRecord;$('nextSample').onclick=addSample;$('plants').innerHTML=species.map(x=>`<button data-p="${x}">${x}</button>`).join('');$('plants').onclick=e=>{if(e.target.dataset.p)$('pp').value=e.target.dataset.p};restore();if(sess){showApp();$('date').value=today();}else showLogin();speechSetup();setInterval(()=>{if(sess&&state?.survey?.id&&!document.hidden)refresh(true)},5000);
})();