(function(){
'use strict';
var KEY='plant_recorder_v46', SNAP1='plant_recorder_snapshot_1', SNAP2='plant_recorder_snapshot_2', SNAP3='plant_recorder_snapshot_3', PREFIX='PLANT-RECORDER-BACKUP-V48:';
var lastSpeech='', lastSaved='';
function E(id){return document.getElementById(id)}
function isWechat(){return /MicroMessenger/i.test(navigator.userAgent||'')}
function cnNum(raw){var s=String(raw||'').trim(),m={'零':0,'〇':0,'一':1,'二':2,'两':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9},p,a,b,i;if(/^\d+(?:\.\d+)?$/.test(s))return Number(s);if(s.indexOf('点')>0){p=s.split('点');a=cnNum(p[0]);if(a==null)return null;b='';for(i=0;i<p[1].length;i++){if(m[p[1].charAt(i)]==null)return null;b+=String(m[p[1].charAt(i)])}return Number(String(a)+'.'+b)}if(s==='十')return 10;if(s.indexOf('十')>=0){p=s.split('十');a=p[0]?(m[p[0]]==null?null:m[p[0]]):1;b=p[1]?(m[p[1]]==null?null:m[p[1]]):0;if(a==null||b==null)return null;return a*10+b}if(m[s]!=null)return m[s];if(s==='百'||s==='一百')return 100;return null}
function norm(t){return String(t||'').replace(/[，、；;]/g,',').replace(/生长壮况|生长状态|生长情况/g,'生长状况').replace(/长式|长是|涨势/g,'长势').replace(/植株高度|株高|平均高/g,'高度')}
function after(t,labels){var i,re,m,v;for(i=0;i<labels.length;i++){re=new RegExp(labels[i]+'(?:大概|大约|约)?[是为：:\\s]*([零〇一二两三四五六七八九十百点\\d\\.]+)(?:厘米|cm|CM|分|级)?');m=t.match(re);if(m){v=cnNum(m[1]);if(v!=null)return v}}return null}
function trailingGrowth(t){var m=t.match(/(?:野生自生|野生|人工栽培|人工|栽培)[,\s]*(?:长势|生长状况)?[是为：\s]*([一二三四五1-5])(?:级|分)?\s*[。.]?$/),v;if(m){v=cnNum(m[1]);return v>=1&&v<=5?v:null}m=t.match(/(?:长势|生长状况|状态)[是为：\s]*([一二三四五1-5])(?:级|分)?/);if(m){v=cnNum(m[1]);return v>=1&&v<=5?v:null}return null}
function fallbackHeight(t){var m=t.match(/^[^,，]*[,\s]+([零〇一二两三四五六七八九十百点\d\.]+)(?:厘米|cm|CM)?[,\s]+(?:盖度|覆盖)/);return m?cnNum(m[1]):null}
function improveSpeech(){var box=E('speech'),ph=E('ph'),pg=E('pg'),pn=E('pn'),hint=E('hint');if(!box)return;var text=box.value;if(!text||text===lastSpeech)return;lastSpeech=text;text=norm(text);var h=after(text,['平均高度','高度','高']);if(h==null)h=fallbackHeight(text);var gr=after(text,['长势评分','长势','生长状况评分','生长状况','状态']);if(gr==null)gr=trailingGrowth(text);if(ph&&!ph.value&&h!=null)ph.value=String(h);if(pg&&!pg.value&&gr>=1&&gr<=5)pg.value=String(gr);if(pn&&pn.value){var miss=[];if(!E('pp').value)miss.push('种名');if(!ph.value)miss.push('高度');if(!pg.value)miss.push('生长状况');pn.value=miss.length?'待确认：'+miss.join('、'):''}if(hint&&ph&&pg&&ph.value&&pg.value)hint.innerHTML='<span class="good">✅ 高度和生长状况已补充识别，可修改后加入</span>'}
function rotateSnapshot(){var cur='';try{if(window.recorderPersist)window.recorderPersist();cur=localStorage.getItem(KEY)||'';if(!cur||cur===lastSaved)return;var old1=localStorage.getItem(SNAP1)||'';if(old1&&old1!==cur){localStorage.setItem(SNAP3,localStorage.getItem(SNAP2)||'');localStorage.setItem(SNAP2,old1)}localStorage.setItem(SNAP1,cur);lastSaved=cur}catch(e){}}
function backupText(){rotateSnapshot();var raw=localStorage.getItem(KEY)||'';return PREFIX+encodeURIComponent(raw)}
function showText(text,msg){var ta=E('backupText');if(!ta)return;ta.style.display='block';ta.value=text;ta.focus();ta.select();if(E('backupMsg'))E('backupMsg').textContent=msg||'备份文本已显示，可长按全选复制。'}
function legacyCopy(text){var ta=E('backupText');try{if(ta){ta.value=text;ta.style.display='block';ta.focus();ta.select();document.execCommand('copy');if(E('backupMsg'))E('backupMsg').textContent='✅ 已复制全部数据备份。';return true}}catch(e){}return false}
function copyBackup(){var text=backupText();showText(text,'正在复制完整备份…');try{if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(function(){if(E('backupMsg'))E('backupMsg').textContent='✅ 已复制全部数据备份。可在系统浏览器粘贴恢复。'},function(){if(!legacyCopy(text)&&E('backupMsg'))E('backupMsg').textContent='⚠️ 自动复制被微信拦截，请长按下方文本全选复制。'});return text}}catch(e){}if(!legacyCopy(text)&&E('backupMsg'))E('backupMsg').textContent='⚠️ 自动复制被微信拦截，请长按下方文本全选复制。';return text}
function decode(text){var t=String(text||'').trim(),raw=t.indexOf(PREFIX)===0?decodeURIComponent(t.substring(PREFIX.length)):t,obj=JSON.parse(raw);if(!obj||!obj.grids||!obj.grids.length)throw new Error('备份内容格式不正确');return raw}
function restore(){var ta=E('backupText');if(!ta||!ta.value.trim())return alert('请把备份码粘贴到下面文本框');try{var raw=decode(ta.value);if(!confirm('确定用这份备份恢复当前浏览器的数据吗？'))return;var cur=localStorage.getItem(KEY)||'';if(cur)localStorage.setItem(SNAP2,cur);localStorage.setItem(KEY,raw);if(E('backupMsg'))E('backupMsg').textContent='✅ 恢复成功，页面将重新载入。';setTimeout(function(){location.reload()},300)}catch(e){alert('恢复失败：'+e.message)}}
function restoreSnapshot(){var raw=localStorage.getItem(SNAP1)||localStorage.getItem(SNAP2)||localStorage.getItem(SNAP3)||'';if(!raw)return alert('没有找到本机快照');if(!confirm('恢复最近一次本机快照？'))return;localStorage.setItem(KEY,raw);location.reload()}
function setupPanel(){var h=document.querySelector('h1');if(h)h.textContent='🌿 植物样方语音记录器 V4.8';var footer=document.querySelector('.footer'),card=document.createElement('div');card.className='card';card.innerHTML='<div class="title">🛡️ 数据保险箱</div><div id="wechatWarn" class="warn" style="display:none;margin-bottom:8px"><b>检测到微信内置浏览器。</b> 微信可能拦截Excel下载，但当前数据还在这里。请先点“复制全部数据备份”，再点微信右上角“在浏览器打开”，在系统浏览器中粘贴恢复后再导出Excel。<b>现在不要清理微信缓存。</b></div><div class="row"><button id="copyBackup" class="primary">复制全部数据备份</button><button id="showBackup" class="soft">显示备份文本</button><button id="restoreBackup" class="soft">从备份恢复</button><button id="restoreSnap" class="soft">恢复最近快照</button></div><textarea id="backupText" placeholder="备份码会显示在这里；换到系统浏览器后，也可以把备份码粘贴到这里恢复" style="display:none;margin-top:8px;min-height:130px"></textarea><div id="backupMsg" class="status" style="margin-top:6px">页面会自动保留本机快照。每天结束前建议点一次“复制全部数据备份”。</div>';if(footer&&footer.parentNode)footer.parentNode.insertBefore(card,footer);else document.body.appendChild(card);E('copyBackup').onclick=copyBackup;E('showBackup').onclick=function(){showText(backupText(),'完整备份已显示，可长按复制。')};E('restoreBackup').onclick=restore;E('restoreSnap').onclick=restoreSnapshot;if(isWechat())E('wechatWarn').style.display='block';window.copyPlantBackup=copyBackup;window.isWeChat=isWechat}
function setupExportGuard(){var btn=E('xlsx');if(!btn)return;var old=btn.onclick;btn.onclick=function(ev){if(isWechat()){copyBackup();if(E('backupMsg'))E('backupMsg').textContent='✅ 已先保存数据备份。微信若没有弹出文件，请用右上角“在浏览器打开”后恢复并导出。'}if(typeof old==='function')return old.call(this,ev)}}
setupPanel();setupExportGuard();setInterval(improveSpeech,250);setInterval(rotateSnapshot,5000);document.addEventListener('visibilitychange',function(){if(document.hidden)rotateSnapshot()});window.addEventListener('pagehide',rotateSnapshot);
})();