(function(){
'use strict';
var SCORE_NAMES=['感知绿化程度','感知植物多样性','植物色彩丰富度','景观自然感','景观设计层次感','软硬景观协调性','街道尺度宜人度','感知视线通透性','整洁感','基础设施丰富度','铺装质量感知','安全感'];
function E(id){return document.getElementById(id)}
function state(){if(window.recorderPersist)window.recorderPersist();return window.recorderState?window.recorderState():null}
function xml(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function shortDate(v){var m=String(v||'').match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);return m?(Number(m[2])+'.'+Number(m[3])):(v||'')}
function safeSheetName(s){return String(s||'样地').replace(/[\\\/?*\[\]:]/g,'').substring(0,31)||'样地'}
function allSites(g){var out=[],i,j,r;for(i=0;i<(g&&g.roads?g.roads.length:0);i++){r=g.roads[i];for(j=0;j<(r.sites||[]).length;j++)out.push({road:r,site:r.sites[j]})}return out}
function uniqueNames(items){var used={},names=[],i,base,n,name;for(i=0;i<items.length;i++){base=safeSheetName((items[i].road.code||'道路')+'-'+(items[i].site.code||'')+'样地');name=base;n=2;while(used[name]){name=safeSheetName(base.substring(0,Math.max(1,27-String(n).length))+'-'+n);n++}used[name]=1;names.push(name)}return names}
function col(n){var s='';while(n>0){n--;s=String.fromCharCode(65+(n%26))+s;n=Math.floor(n/26)}return s}
function cell(ref,value,style){var v=value==null?'':String(value),sp=(/^\s|\s$/.test(v)?' xml:space="preserve"':'');return '<c r="'+ref+'" s="'+(style||0)+'" t="inlineStr"><is><t'+sp+'>'+xml(v)+'</t></is></c>'}
function row(r,cells,height){var keys=[],k,i,body='';for(k in cells)if(Object.prototype.hasOwnProperty.call(cells,k))keys.push(Number(k));keys.sort(function(a,b){return a-b});for(i=0;i<keys.length;i++)body+=cell(col(keys[i])+r,cells[keys[i]].v,cells[keys[i]].s);return '<row r="'+r+'"'+(height?' ht="'+height+'" customHeight="1"':'')+'>'+body+'</row>'}
function rowAll(r,value,style,count,height){var o={},i;for(i=1;i<=count;i++)o[i]={v:value,s:style};return row(r,o,height)}
function sheetXml(g,road,site){
 var rows=[],r=1,i,j,q,z,vals,cells;
 rows.push(rowAll(1,'',1,19,20));rows.push(rowAll(2,'',1,19,20));rows.push(rowAll(3,'',1,19,20));rows.push(rowAll(4,'',1,19,20));rows.push(rowAll(5,'',1,19,20));rows.push(rowAll(6,'',1,19,20));
 var loc=site.loc||((g.grid||'')+'网格'+(road.code||'')+(site.code||'')+'样地');
 var meta=[['调研地点：',loc],['调研日期：',shortDate(g.date)],['所属行政区：',g.district||''],['道路走向',road.direction||''],['机动车道宽度',road.motor||''],['慢行道宽度',road.slow||'']];
 for(i=0;i<meta.length;i++){
  rows[i]=row(i+1,{1:{v:meta[i][0],s:2},2:{v:meta[i][1],s:2},3:{v:i===0?((site.code||'')+'样地'):(i===1?('道路：'+(road.code||'')):(i===2&&road.note?('备注：'+road.note):'')),s:2}},20);
 }
 rows.push(row(7,{}));rows.push(row(8,{}));
 var heads=['郁闭度 0-1','优势物种','群落空间建构（乔木、灌木、草本）','样地覆盖物','水元素','其他生物','管理维护频率'].concat(SCORE_NAMES);
 var values=[site.canopy,site.dominant,site.community,site.material,site.water,site.bio,site.maint].concat(SCORE_NAMES.map(function(n){return site.scores&&site.scores[n]!=null?site.scores[n]:''}));
 cells={};for(i=0;i<19;i++)cells[i+1]={v:heads[i],s:3};rows.push(row(9,cells,36));cells={};for(i=0;i<19;i++)cells[i+1]={v:values[i],s:4};rows.push(row(10,cells,24));
 rows.push(row(11,{}));rows.push(row(12,{}));rows.push(row(13,{2:{v:'记得拍摄四个方向街景图片',s:5}},22));rows.push(row(14,{}));rows.push(row(15,{}));
 r=16;
 for(i=0;i<(site.samples||[]).length;i++){
  q=site.samples[i];rows.push(rowAll(r,'',6,19,22));rows[rows.length-1]=row(r,{1:{v:'样方编号：',s:6},2:{v:q.code||'',s:6}},22);r++;
  vals=['序号','种名','平均高度（cm）','长*宽（cm）','盖度（%）','植物类型','生长状况'];cells={};for(j=0;j<7;j++)cells[j+1]={v:vals[j],s:7};rows.push(row(r,cells,24));r++;
  for(j=0;j<(q.records||[]).length;j++){
   z=q.records[j];vals=[j+1,z.plant||'',z.height||'',z.dims||'',z.cover||'',z.type||'',z.growth||''];cells={};for(var x=0;x<7;x++)cells[x+1]={v:vals[x],s:8};rows.push(row(r,cells,22));r++;
  }
 }
 var cols='<cols><col min="1" max="1" width="14" customWidth="1"/><col min="2" max="2" width="18" customWidth="1"/><col min="3" max="3" width="27" customWidth="1"/><col min="4" max="4" width="19" customWidth="1"/><col min="5" max="5" width="13" customWidth="1"/><col min="6" max="7" width="16" customWidth="1"/><col min="8" max="19" width="15" customWidth="1"/></cols>';
 return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="10" topLeftCell="A11" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="18"/>'+cols+'<sheetData>'+rows.join('')+'</sheetData><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>';
}
function stylesXml(){return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="11"/><name val="Microsoft YaHei"/></font><font><b/><sz val="11"/><name val="Microsoft YaHei"/></font><font><b/><color rgb="FFFF0000"/><sz val="11"/><name val="Microsoft YaHei"/></font></fonts><fills count="6"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE2F0D9"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF4CCCC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF2CC"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFD9D9D9"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFB7C1BA"/></left><right style="thin"><color rgb="FFB7C1BA"/></right><top style="thin"><color rgb="FFB7C1BA"/></top><bottom style="thin"><color rgb="FFB7C1BA"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="0" fillId="2" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="3" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="2" fillId="4" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="1" fillId="0" borderId="1" xfId="0" applyFont="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="5" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'}
function workbookXml(names){var s='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView xWindow="0" yWindow="0" windowWidth="16000" windowHeight="9000"/></bookViews><sheets>';for(var i=0;i<names.length;i++)s+='<sheet name="'+xml(names[i])+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>';return s+'</sheets><calcPr calcId="191029"/></workbook>'}
function workbookRels(n){var s='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">',i;for(i=0;i<n;i++)s+='<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>';s+='<Relationship Id="rId'+(n+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>';return s}
function contentTypes(n){var s='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>';for(var i=0;i<n;i++)s+='<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>';return s+'</Types>'}
function rootRels(){return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'}
function utf8(s){if(window.TextEncoder)return new TextEncoder().encode(s);var out=[],i,c;for(i=0;i<s.length;i++){c=s.charCodeAt(i);if(c<128)out.push(c);else if(c<2048){out.push(192|(c>>6),128|(c&63))}else if(c>=55296&&c<=56319&&i+1<s.length){var d=s.charCodeAt(++i),u=65536+((c-55296)<<10)+(d-56320);out.push(240|(u>>18),128|((u>>12)&63),128|((u>>6)&63),128|(u&63))}else out.push(224|(c>>12),128|((c>>6)&63),128|(c&63))}return new Uint8Array(out)}
var CRC_TABLE=null;function crc32(bytes){if(!CRC_TABLE){CRC_TABLE=[];for(var n=0;n<256;n++){var c=n;for(var k=0;k<8;k++)c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1);CRC_TABLE[n]=c>>>0}}var crc=0xFFFFFFFF;for(var i=0;i<bytes.length;i++)crc=CRC_TABLE[(crc^bytes[i])&255]^(crc>>>8);return (crc^0xFFFFFFFF)>>>0}
function w16(a,p,v){a[p]=v&255;a[p+1]=(v>>>8)&255}function w32(a,p,v){a[p]=v&255;a[p+1]=(v>>>8)&255;a[p+2]=(v>>>16)&255;a[p+3]=(v>>>24)&255}
function dosTime(){var d=new Date(),time=((d.getHours()&31)<<11)|((d.getMinutes()&63)<<5)|((Math.floor(d.getSeconds()/2))&31),date=(((d.getFullYear()-1980)&127)<<9)|(((d.getMonth()+1)&15)<<5)|(d.getDate()&31);return{time:time,date:date}}
function zip(files){var parts=[],central=[],offset=0,dt=dosTime(),i;for(i=0;i<files.length;i++){var name=utf8(files[i].name),data=utf8(files[i].data),crc=crc32(data),h=new Uint8Array(30+name.length);w32(h,0,0x04034b50);w16(h,4,20);w16(h,6,0x0800);w16(h,8,0);w16(h,10,dt.time);w16(h,12,dt.date);w32(h,14,crc);w32(h,18,data.length);w32(h,22,data.length);w16(h,26,name.length);w16(h,28,0);h.set(name,30);parts.push(h,data);var cd=new Uint8Array(46+name.length);w32(cd,0,0x02014b50);w16(cd,4,20);w16(cd,6,20);w16(cd,8,0x0800);w16(cd,10,0);w16(cd,12,dt.time);w16(cd,14,dt.date);w32(cd,16,crc);w32(cd,20,data.length);w32(cd,24,data.length);w16(cd,28,name.length);w16(cd,30,0);w16(cd,32,0);w16(cd,34,0);w16(cd,36,0);w32(cd,38,0);w32(cd,42,offset);cd.set(name,46);central.push(cd);offset+=h.length+data.length}var centralStart=offset,centralSize=0;for(i=0;i<central.length;i++){parts.push(central[i]);centralSize+=central[i].length}var end=new Uint8Array(22);w32(end,0,0x06054b50);w16(end,4,0);w16(end,6,0);w16(end,8,files.length);w16(end,10,files.length);w32(end,12,centralSize);w32(end,16,centralStart);w16(end,20,0);parts.push(end);return new Blob(parts,{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function buildXlsx(g){var list=allSites(g);if(!list.length)throw new Error('当前网格没有样地');var names=uniqueNames(list),files=[{name:'[Content_Types].xml',data:contentTypes(list.length)},{name:'_rels/.rels',data:rootRels()},{name:'xl/workbook.xml',data:workbookXml(names)},{name:'xl/_rels/workbook.xml.rels',data:workbookRels(list.length)},{name:'xl/styles.xml',data:stylesXml()}];for(var i=0;i<list.length;i++)files.push({name:'xl/worksheets/sheet'+(i+1)+'.xml',data:sheetXml(g,list[i].road,list[i].site)});return zip(files)}
function xlsXml(g){var list=allSites(g),names=uniqueNames(list),book='<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Default"><Font ss:FontName="Microsoft YaHei" ss:Size="11"/></Style><Style ss:ID="green"><Font ss:Bold="1"/><Interior ss:Color="#E2F0D9" ss:Pattern="Solid"/></Style><Style ss:ID="pink"><Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/><Font ss:Bold="1"/><Interior ss:Color="#F4CCCC" ss:Pattern="Solid"/></Style><Style ss:ID="center"><Alignment ss:Horizontal="Center" ss:Vertical="Center"/></Style><Style ss:ID="red"><Font ss:Bold="1" ss:Color="#FF0000"/></Style><Style ss:ID="yellow"><Font ss:Bold="1" ss:Color="#FF0000"/><Interior ss:Color="#FFF2CC" ss:Pattern="Solid"/></Style><Style ss:ID="gray"><Alignment ss:Horizontal="Center"/><Interior ss:Color="#D9D9D9" ss:Pattern="Solid"/></Style></Styles>',i,j,k,o,r,s,q,z,rows;
 function xr(vals,styles){var x='<Row>';for(var a=0;a<vals.length;a++)x+='<Cell'+(styles&&styles[a]?' ss:StyleID="'+styles[a]+'"':'')+'><Data ss:Type="String">'+xml(vals[a])+'</Data></Cell>';return x+'</Row>'}
 for(i=0;i<list.length;i++){o=list[i];r=o.road;s=o.site;rows='';rows+=xr(['调研地点：',s.loc||((g.grid||'')+'网格'+(r.code||'')+(s.code||'')+'样地'),(s.code||'')+'样地'],['green','green','green']);rows+=xr(['调研日期：',shortDate(g.date),'道路：'+(r.code||'')],['green','green','green']);rows+=xr(['所属行政区：',g.district||'',r.note?('备注：'+r.note):''],['green','green','green']);rows+=xr(['道路走向',r.direction||''],['green','green']);rows+=xr(['机动车道宽度',r.motor||''],['green','green']);rows+=xr(['慢行道宽度',r.slow||''],['green','green']);rows+=xr([])+xr([]);var hh=['郁闭度 0-1','优势物种','群落空间建构（乔木、灌木、草本）','样地覆盖物','水元素','其他生物','管理维护频率'].concat(SCORE_NAMES),vv=[s.canopy,s.dominant,s.community,s.material,s.water,s.bio,s.maint].concat(SCORE_NAMES.map(function(n){return s.scores&&s.scores[n]!=null?s.scores[n]:''}));rows+=xr(hh,new Array(19).fill('pink'));rows+=xr(vv,new Array(19).fill('center'));rows+=xr([])+xr([])+xr(['','记得拍摄四个方向街景图片'],['','red'])+xr([])+xr([]);for(j=0;j<(s.samples||[]).length;j++){q=s.samples[j];rows+=xr(['样方编号：',q.code],['yellow','yellow']);rows+=xr(['序号','种名','平均高度（cm）','长*宽（cm）','盖度（%）','植物类型','生长状况']);for(k=0;k<(q.records||[]).length;k++){z=q.records[k];rows+=xr([k+1,z.plant,z.height,z.dims,z.cover,z.type,z.growth],new Array(7).fill('gray'))}}book+='<Worksheet ss:Name="'+xml(names[i])+'"><Table>'+rows+'</Table></Worksheet>'}return book+'</Workbook>'}
function saveBlob(blob,name){
 try{var file=new File([blob],name,{type:blob.type||'application/octet-stream'});if(navigator.canShare&&navigator.share&&navigator.canShare({files:[file]})){navigator.share({files:[file],title:name}).catch(function(err){if(!err||err.name!=='AbortError')fallback(blob,name)});return}}catch(e){}
 fallback(blob,name)
}
function fallback(blob,name){try{var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(url);if(a.parentNode)a.parentNode.removeChild(a)},4000)}catch(e){alert('文件已生成，但浏览器阻止保存。请在Safari/Chrome中打开后重试。')}}
function xlsx(){var g=state(),btn=E('xlsx'),old=btn.textContent;if(!g)return alert('当前没有网格数据');btn.disabled=true;btn.textContent='正在生成完整XLSX…';setTimeout(function(){try{var blob=buildXlsx(g),name=(g.date||'今日')+'_网格'+(g.grid||'未编号')+'_样方调查汇总.xlsx';saveBlob(blob,name);btn.textContent='✅ XLSX已生成';setTimeout(function(){btn.textContent=old;btn.disabled=false},1400)}catch(e){console.error(e);alert('XLSX生成失败：'+e.message+'。可先使用左侧兼容版XLS。');btn.textContent=old;btn.disabled=false}},30)}
function xls(){var g=state();if(!g)return alert('当前没有网格数据');try{saveBlob(new Blob(['\ufeff',xlsXml(g)],{type:'application/vnd.ms-excel;charset=utf-8'}),(g.date||'今日')+'_网格'+(g.grid||'未编号')+'_样方调查汇总.xls')}catch(e){alert('兼容版XLS生成失败：'+e.message)}}
if(E('xlsx'))E('xlsx').onclick=xlsx;if(E('xls'))E('xls').onclick=xls;
})();