(function(){
'use strict';
var KEY='plant_recorder_v46',DB='plant_recorder_safety_v52',STORE='backups',READY=false,lastRaw='';
function E(id){return document.getElementById(id)}
function stats(raw){try{var o=JSON.parse(raw);if(!o||!Array.isArray(o.grids))return null;var roads=0,sites=0,samples=0,records=0,i,j,k,l;for(i=0;i<o.grids.length;i++){var g=o.grids[i];if(!Array.isArray(g.roads))continue;roads+=g.roads.length;for(j=0;j<g.roads.length;j++){var r=g.roads[j];if(!Array.isArray(r.sites))continue;sites+=r.sites.length;for(k=0;k<r.sites.length;k++){var s=r.sites[k];if(!Array.isArray(s.samples))continue;samples+=s.samples.length;for(l=0;l<s.samples.length;l++)records+=Array.isArray(s.samples[l].records)?s.samples[l].records.length:0}}}return{grids:o.grids.length,roads:roads,sites:sites,samples:samples,records:records,score:records*100000+samples*1000+sites*10+o.grids.length}}catch(e){return null}}
function openDB(cb){if(!window.indexedDB)return cb(new Error('当前浏览器不支持IndexedDB'));var req=indexedDB.open(DB,1);req.onupgradeneeded=function(){var d=req.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=function(){cb(null,req.result)};req.onerror=function(){cb(req.error||new Error('IndexedDB打开失败'))}}
function getAll(cb){openDB(function(err,d){if(err)return cb(err,[]);var tx=d.transaction(STORE,'readonly'),st=tx.objectStore(STORE),req=st.getAll();req.onsuccess=function(){cb(null,req.result||[])};req.onerror=function(){cb(req.error||new Error('读取失败'),[])};tx.oncomplete=function(){d.close()}})}
function putEntry(entry,cb){openDB(function(err,d){if(err){if(cb)cb(err);return}var tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(entry);tx.oncomplete=function(){d.close();if(cb)cb(null)};tx.onerror=function(){d.close();if(cb)cb(tx.error||new Error('写入失败'))}})}
function findById(arr,id){var i;for(i=0;i<arr.length;i++)if(arr[i].id===id)return arr[i];return null}
function mirror(raw){var st=stats(raw);if(!st||!READY||raw===lastRaw)return;lastRaw=raw;getAll(function(err,arr){if(err)return;var cur=findById(arr,'current'),s1=findById(arr,'snap1'),s2=findById(arr,'snap2');if(cur&&cur.raw&&cur.raw!==raw){if(s2&&s2.raw)putEntry({id:'snap3',raw:s2.raw,time:s2.time||Date.now()});if(s1&&s1.raw)putEntry({id:'snap2',raw:s1.raw,time:s1.time||Date.now()});putEntry({id:'snap1',raw:cur.raw,time:cur.time||Date.now()})}putEntry({id:'current',raw:raw,time:Date.now(),records:st.records,sites:st.sites,samples:st.samples})})}
function bestEntry(arr){var best=null,bestSt=null,i,st;for(i=0;i<arr.length;i++){if(!arr[i]||!arr[i].raw)continue;st=stats(arr[i].raw);if(!st)continue;if(!best||st.score>bestSt.score||(st.score===bestSt.score&&(arr[i].time||0)>(best.time||0))){best=arr[i];bestSt=st}}return best?{entry:best,st:bestSt}:null}
function setHealth(text,ok){var el=E('storageHealth');if(!el)return;el.textContent=text;el.style.color=ok?'#26734d':'#a33'}
function addHealth(){if(E('storageHealth'))return;var card=document.createElement('div');card.className='card';card.innerHTML='<div class="title">💾 本机存储保护</div><div id="storageHealth" class="status">正在检查双重存储……</div><div class="status" style="margin-top:6px">V5.3 会同时保存到 localStorage 和 IndexedDB，并保留多份快照；另提供手机独立保险文件作为第三层保障。</div>';var footer=document.querySelector('.footer');if(footer&&footer.parentNode)footer.parentNode.insertBefore(card,footer)}
function requestPersist(){try{if(navigator.storage&&navigator.storage.persist){navigator.storage.persist().then(function(granted){setHealth(granted?'✅ 双重存储已启用，并获得持久化保护':'✅ 双重存储已启用；浏览器未授予持久化权限，请定期保存手机保险文件',true)},function(){setHealth('✅ 双重存储已启用；浏览器未授予持久化权限',true)})}else setHealth('✅ 双重存储已启用；此浏览器不支持持久化权限接口',true)}catch(e){setHealth('✅ 双重存储已启用',true)}}
function loadV53(){if(document.getElementById('externalBackupV53Script'))return;var sc=document.createElement('script');sc.id='externalBackupV53Script';sc.src='external-backup-v53.js?v=53';document.body.appendChild(sc)}
function boot(){var h=document.querySelector('h1');if(h)h.textContent='🌿 植物样方语音记录器 V5.3';document.title='植物样方语音记录器 V5.3';addHealth();loadV53();var local='';try{local=localStorage.getItem(KEY)||''}catch(e){}var lst=stats(local);getAll(function(err,arr){if(err){READY=true;setHealth('⚠️ IndexedDB不可用，当前仅能使用普通本机存储',false);return}var best=bestEntry(arr);if(best&&(!lst||best.st.score>lst.score)){try{localStorage.setItem('plant_recorder_before_auto_recover_v52',local||'');localStorage.setItem(KEY,best.entry.raw);setHealth('✅ 检测到更完整的安全副本，正在自动恢复：'+best.st.records+'条植物记录',true);setTimeout(function(){location.reload()},400);return}catch(e2){}}READY=true;if(local)mirror(local);requestPersist()})}
setInterval(function(){if(!READY)return;var raw='';try{raw=localStorage.getItem(KEY)||''}catch(e){}if(raw)mirror(raw)},1500);
document.addEventListener('visibilitychange',function(){if(document.hidden){var raw='';try{raw=localStorage.getItem(KEY)||''}catch(e){}if(raw)mirror(raw)}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();